# Qutebrowser pywal template with improved command palette contrast
# Save this as ~/.config/wal/templates/qutebrowser-config.py

# Load existing settings
config.load_autoconfig()

# Colors generated by pywal
base16 = {{
    'base00': '{color0}',  # background
    'base01': '{color8}',  # lighter background
    'base02': '{color0}',  # selection background
    'base03': '{color8}',  # comments, invisibles
    'base04': '{color7}',  # dark foreground
    'base05': '{color7}',  # default foreground
    'base06': '{color15}', # light foreground
    'base07': '{color15}', # light background
    'base08': '{color1}',  # red
    'base09': '{color9}',  # orange
    'base0A': '{color3}',  # yellow
    'base0B': '{color2}',  # green
    'base0C': '{color6}',  # cyan
    'base0D': '{color4}',  # blue
    'base0E': '{color5}',  # purple
    'base0F': '{color1}',  # brown
}}

# Apply colors to qutebrowser with improved command palette contrast
c.colors.completion.category.bg = base16['base01']
c.colors.completion.category.border.bottom = base16['base03']
c.colors.completion.category.border.top = base16['base03']
c.colors.completion.category.fg = base16['base0D']
c.colors.completion.even.bg = base16['base00']
c.colors.completion.odd.bg = base16['base00']
c.colors.completion.fg = base16['base05']
c.colors.completion.item.selected.bg = base16['base0D']
c.colors.completion.item.selected.border.bottom = base16['base0D']
c.colors.completion.item.selected.border.top = base16['base0D']
c.colors.completion.item.selected.fg = base16['base00']
c.colors.completion.match.fg = base16['base0A']
c.colors.completion.scrollbar.bg = base16['base01']
c.colors.completion.scrollbar.fg = base16['base03']

# Downloads
c.colors.downloads.bar.bg = base16['base00']
c.colors.downloads.error.bg = base16['base08']
c.colors.downloads.error.fg = base16['base05']
c.colors.downloads.start.bg = base16['base0D']
c.colors.downloads.start.fg = base16['base00']
c.colors.downloads.stop.bg = base16['base0C']
c.colors.downloads.stop.fg = base16['base00']
c.colors.downloads.system.bg = 'none'

# Hints
c.colors.hints.bg = base16['base0A']
c.colors.hints.fg = base16['base00']
c.colors.hints.match.fg = base16['base05']

# Keyhint widget
c.colors.keyhint.bg = base16['base00']
c.colors.keyhint.fg = base16['base05']
c.colors.keyhint.suffix.fg = base16['base0B']

# Messages
c.colors.messages.error.bg = base16['base08']
c.colors.messages.error.border = base16['base08']
c.colors.messages.error.fg = base16['base00']
c.colors.messages.info.bg = base16['base00']
c.colors.messages.info.border = base16['base00']
c.colors.messages.info.fg = base16['base05']
c.colors.messages.warning.bg = base16['base0E']
c.colors.messages.warning.border = base16['base0E']
c.colors.messages.warning.fg = base16['base05']

# Prompts
c.colors.prompts.bg = base16['base00']
c.colors.prompts.border = '1px solid ' + base16['base03']  # Changed: visible border
c.colors.prompts.fg = base16['base05']
c.colors.prompts.selected.bg = base16['base0D']            # Changed: use accent color

# Statusbar
c.colors.statusbar.caret.bg = base16['base0E']
c.colors.statusbar.caret.fg = base16['base00']
c.colors.statusbar.caret.selection.bg = base16['base0D']
c.colors.statusbar.caret.selection.fg = base16['base00']
c.colors.statusbar.command.bg = base16['base00']
c.colors.statusbar.command.fg = base16['base05']
c.colors.statusbar.command.private.bg = base16['base00']
c.colors.statusbar.command.private.fg = base16['base05']
c.colors.statusbar.insert.bg = base16['base0B']
c.colors.statusbar.insert.fg = base16['base00']
c.colors.statusbar.normal.bg = base16['base00']
c.colors.statusbar.normal.fg = base16['base05']
c.colors.statusbar.passthrough.bg = base16['base0C']
c.colors.statusbar.passthrough.fg = base16['base00']
c.colors.statusbar.private.bg = base16['base01']
c.colors.statusbar.private.fg = base16['base05']
c.colors.statusbar.progress.bg = base16['base0D']
c.colors.statusbar.url.error.fg = base16['base08']
c.colors.statusbar.url.fg = base16['base05']
c.colors.statusbar.url.hover.fg = base16['base0C']
c.colors.statusbar.url.success.http.fg = base16['base05']
c.colors.statusbar.url.success.https.fg = base16['base0B']
c.colors.statusbar.url.warn.fg = base16['base0E']

# Tabs
c.colors.tabs.bar.bg = base16['base00']
c.colors.tabs.even.bg = base16['base01']
c.colors.tabs.even.fg = base16['base05']
c.colors.tabs.indicator.error = base16['base08']
c.colors.tabs.indicator.start = base16['base0D']
c.colors.tabs.indicator.stop = base16['base0C']
c.colors.tabs.indicator.system = 'none'
c.colors.tabs.odd.bg = base16['base01']
c.colors.tabs.odd.fg = base16['base05']
c.colors.tabs.selected.even.bg = base16['base02']
c.colors.tabs.selected.even.fg = base16['base05']
c.colors.tabs.selected.odd.bg = base16['base02']
c.colors.tabs.selected.odd.fg = base16['base05']

# Webpage colors
#c.colors.webpage.bg = base16['base00']
c.colors.webpage.preferred_color_scheme = 'dark'
